name: five_flutter_auth_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.3
  video_player: ^2.7.2
  flutter_svg: ^2.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/video/promo.mp4
    - assets/icons/download.svg
    - assets/icons/arrow_right.svg
    - assets/icons/mail.svg
    - assets/icons/facebook.svg
    - assets/icons/apple.svg
    - assets/icons/google.svg
    - assets/icons/eye.svg
    - assets/icons/password.svg
    - assets/icons/user.svg

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: fonts/Gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: fonts/Gilroy/Gilroy-Bold.ttf
          weight: 700
        - asset: fonts/Gilroy/Gilroy-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-Black.ttf
          weight: 900

